config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  namespace :producer do
    get 'users/dashboard', to: 'users#show'
  end

  namespace :admin do
    get 'users/dashboard', to: 'users#show'
  end

  resources :stories, only: [:index] do
    resources :pitches, only: [:new, :create, :show]
  end

  resources :pitches, only: [:index]
  resources :likes_dislikes, only: [:create]
  resources :stations, only: [:show]
  resources :community, only: [:index]
  resources :comments, only: [:create]

  get 'users/edit', to: 'users#edit'
  put 'user', to: 'users#update'
  patch 'user', to: 'users#update'
  get 'users/dashboard', to: 'users#show'

  namespace :users  do
    get '/stations/subscriptions/new', to: 'stations#new', as: 'new_station'
    post '/stations/subscriptions', to: 'stations#create'
    delete '/stations/subscriptions', to: 'stations#destroy'
  end

  get '/auth/twitter', as: :twitter_login
  get '/auth/twitter/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/pitch.rb
class Pitch < ApplicationRecord
  belongs_to :user
  belongs_to :story

  validates :headline , presence: true
  validates :story_url, presence: true
  validates :abstract, presence: true

  def ups
    likes_dislikes.where('ups = ?', true).count
  end

  def downs
    likes_dislikes.where('downs = ?', true).count
  end

  def comments
    Comment.where('pitch_id = ?', id)
  end

  def likes_dislikes
    LikesDislike.where('pitch_id = ?', id)
  end
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  before_action :set_story, only: [:new, :create]

  def index
    @pitches = Pitch.order(created_at: :desc).first(25)
  end

  def new
    @pitch = Pitch.new
  end

  def create
    @pitch = current_user.pitches.new(pitch_params)
    if @pitch.save
      redirect_to story_pitch_path(params[:story_id], @pitch.id)
    else
      flash.now[:danger] = @pitch.errors.full_messages
      render :new
    end
  end

  def show
    @pitch = Pitch.find(params[:id])
    @comment = Comment.new
  end

  private
    def pitch_params
      story = Story.find(params[:story_id])
      {headline:  story.title,
       story_url: story.url,
       abstract:  story.abstract,
       body:      params[:pitch][:body],
       story_id:  story.id,
       ups:       1,
       downs:     0}
    end

    def set_story
      @story = Story.find(params[:story_id])
    end
end

app/controllers/users/pitches_controller.rb
class Users::PitchesContoller < ApplicationController
  def new

  end
end

app/views/pitches/_comment_form.html.erb
<%= form_for @comment do |f| %>
  <%= f.text_area :body, placeholder: 'Comment on this Story' %><br>
  <%= f.hidden_field :pitch_id, {value: @pitch.id} %>
  <%= f.submit 'Submit', class: 'btn btn-default' %>
<% end %>

app/views/pitches/_comments.html.erb
<p class="comment">
  <strong><img src='<%= comment.user.profile_image %>'> <%= comment.user.screen_name %></strong><br>
  &nbsp;&nbsp;<%= comment.body %><br>
  <%= link_to((pluralize comment.ups, 'Like'), likes_dislikes_path(comment_id: comment.id, like: true), method: :post) %> |
  <%= link_to((pluralize comment.downs, 'Dislike'), likes_dislikes_path(comment_id: comment.id, dislike: true), method: :post) %>
  <div class="reply">
    <%= link_to 'Reply', '#reply', onclick: 'return false;' %>
  </div>
  <div class='body' hidden>
    <%= form_for @comment do |f| %>
      <%= f.text_area :body, placeholder: 'Reply' %><br>
      <%= f.hidden_field :reply_id, {value: comment.id} %>
      <%= f.hidden_field :pitch_id, {value: @pitch.id} %>
      <%= f.submit 'Reply', class: 'btn btn-default' %>
    <% end %>
  </div>
</p>
<% comment.replies.each do |comment| %>
<blockquote>
  <%= render partial: 'comments', locals: {comment: comment} %>
</blockquote>
<% end %>

app/views/pitches/index.html.erb
<div class="container">
  <div class="well">
    <table class='table recent-pitches'>
      <h3>Most Recent Pitches</h3>
      <% @pitches.each do |pitch| %>
        <tr>
          <td>
            <%= link_to pitch.headline, story_pitch_path(pitch.story.id, pitch.id) %><br>
            Pitched by <strong><%= pitch.user.screen_name %></strong> |
            <%= pluralize pitch.ups, 'Like' %> |
            <%= pluralize pitch.downs, 'Dislike' %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/pitches/new.html.erb
<div class="container">
  <div class="well">
    <h2>Pitch Story</h2>
    <%= form_for [@story, @pitch] do |f| %>
      <%= f.label :headline %><br>
      <%= @story.title %><br>
      <%= f.label :story_url, "Article URL" %><br>
      <%= link_to @story.url, @story.url %><br>
      <%= f.label :abstract, "Story Summary" %><br>
      <%= @story.abstract %><br>
      <%= f.label :body, "Why is this article important to you?" %><br>
      <%= f.text_area :body %><br>
      <%= f.submit "Pitch Story", class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/pitches/show.html.erb
<div class="container">
  <div class="well">
    <h2 class='headline'><%= @pitch.headline %></h2>
    <h4 class='story_url'><%= link_to 'New York Times Article', @pitch.story_url %></h4>
    <p class='abstract body'>
      <strong>Summary:</strong><br>
      <%= @pitch.abstract %><br><br>
      <% if @pitch.body %>
        <strong><%= @pitch.user.screen_name %>'s Pitch:</strong><br>
        <%= @pitch.body %>
      <% end %>
    </p>
    <p class='votes'>
      <div class='ups downs'>
        <%= link_to((pluralize @pitch.ups, 'Like'), likes_dislikes_path(pitch_id: @pitch.id, like: true), method: :post) %> | 
        <%= link_to((pluralize @pitch.downs, 'Dislike'), likes_dislikes_path(pitch_id: @pitch.id, dislike: true), method: :post) %>
      </div>
    </p>
    <div class='comments'>
      <h4>Comments</h4>
      <%= render partial: 'comment_form' %>
      <% @pitch.comments.each do |comment| %>
      <blockquote>
        <%= render partial: 'comments', locals: {comment: comment} %>
      </blockquote>
      <% end %>
    </div>
  </div>
</div>