config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  namespace :producer do
    get 'users/dashboard', to: 'users#show'
  end

  namespace :admin do
    get 'users/dashboard', to: 'users#show'
  end

  resources :stories, only: [:index] do
    resources :pitches, only: [:new, :create, :show]
  end

  resources :pitches, only: [:index]
  resources :likes_dislikes, only: [:create]
  resources :stations, only: [:show]
  resources :community, only: [:index]
  resources :comments, only: [:create]

  get 'users/edit', to: 'users#edit'
  put 'user', to: 'users#update'
  patch 'user', to: 'users#update'
  get 'users/dashboard', to: 'users#show'

  namespace :users  do
    get '/stations/subscriptions/new', to: 'stations#new', as: 'new_station'
    post '/stations/subscriptions', to: 'stations#create'
    delete '/stations/subscriptions', to: 'stations#destroy'
  end

  get '/auth/twitter', as: :twitter_login
  get '/auth/twitter/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/views/shared/_base_dashboard.html.erb
<h1>Welcome, <%= current_user.screen_name %></h1>
<div class="row">
  <div class="col-md-4 profile-container">
    <p>
      <img src="<%= current_user.profile_image %>"><br>
      <%= current_user.name %><br>
      <%= current_user.screen_name %><br>
      <%= current_user.location %><br>
      <%= link_to 'Edit Profile', users_edit_path %>
    </p>
    <div class="h-divider">
    </div>
    <p>
      <div class="subscribed">
        <h3>Your Station Subscriptions</h3>
        <% unless current_user.stations.empty? %>
          <%= render partial: 'station_subscriptions' %>
        <% end %>
        <%= link_to 'Subscribe to Stations', users_new_station_path %>        
      </div>
    </p>
  </div>
  <div class="col-md-4 profile-container">
    <table class='table user-pitches'>
      <h3>Your Recent Story Pitches</h3>
      <% current_user.pitches.each do |pitch| %>
      <div class="pitch">
        <tr>
          <td>
            <%= link_to pitch.headline, story_pitch_path(pitch.story.id, pitch.id) %><br>
            <%= pluralize pitch.ups, 'Like' %> |
            <%= pluralize pitch.downs, 'Dislike' %>
          </td>
        </tr>
      </div>
      <% end %>
    </table>
  </div>
  <div class="col-md-4 profile-container">
    <table class='table trending-stories'>
      <h3>Today's Top Trending Stories</h3>
      <% @story_collection.top_five_stories.each do |story| %>
      <div class="story">
        <tr>
          <td>
            <%= link_to story.title, story.url %><br>
            Published <%= story.elapsed_time_since_published %> hours ago |
            <strong><%= link_to 'Pitch Story', new_story_pitch_path(story.id) %></strong>
          </td>
        </tr>
      </div>
      <% end %>
    </table>
  </div>
</div>

app/views/shared/_logged_in_menu.html.erb
<li><%= link_to 'Trending Stories', stories_path %></li>
<li><%= link_to 'Pitches', pitches_path %></li>
<li><%= link_to 'Nearby News Stations', users_new_station_path %></li>
<li><%= link_to current_user.screen_name, users_dashboard_path %></li>
<li><%= link_to 'Logout', logout_path, method: :delete %></li>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/stories">
      <span class='glyphicon glyphicon-pencil' aria-hidden ='true'></span>
      NewZ</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left" action="/stories" method="get">
        <div class="form-group">
          <input type="text" class="form-control" name='search' placeholder="Search Stories">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <%= render partial: 'shared/logged_in_menu' %>
        <% else %>
        <li><a href='#' id='navbar-signin'>Sign In</a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_signin_form.html.erb
<%= react_component 'SigninModal' %>